### PR TITLE
Coloured maps

### PR DESCRIPTION
**Pull request by pure-zero**
Added the ability stylize maps from the admin consoles.  This can be done using java arrays on the textfield.The default is the basic map and on input error the javascript should default to that as well

### CODE REVIEW

**Comment by pure-zero** [comment]
Not sure why flake is failing here, doesn't seem like this branchs fault

**Comment by pure-zero** [comment]
Great looks good now

**Comment by FinalAngel** [comment]
@pure-zero would you be able to rebase?

**Comment by pure-zero** [comment]
@FinalAngel ok sure that's done

**Comment by FinalAngel** [comment]
thank you!

**Pull request merged**
