### PR TITLE
made multiple locations possible

### PR DESCRIPTION
**Pull request by macolo**

### CODE REVIEW

**Comment by macolo** [comment]
any idea why this travis build failed?

**Comment by FinalAngel** [comment]
@macolo seems like something is wrong in your formatting (flake8)

**Comment by vxsx** [comment]
it looks like flake8 checks env for some reason, this change in `tox.ini` should fix it:

```diff 
- exclude = djangocms_googlemap/migrations/*,djangocms_googlemap/south_migrations/*
+ exclude = djangocms_googlemap/migrations/*,djangocms_googlemap/south_migrations/*,.tox/*
```

**Comment by stefanfoulis** [comment]
Is any data lost by this change (e.g will users who already had this plugin with a single location still have that single location after the upgrade?)

There is also https://github.com/aldryn/aldryn-locations/ which already has multiple location support and much more.

**Comment by FinalAngel** [comment]
@stefanfoulis the plan is actually to move to djangocms-googlemap from locations. But you are right, this needs data migration to migrate the old system to the new. Would you be able to do so @macolo ?

**Comment by macolo** [comment]
@FinalAngel I will give it a try.

**Comment by FinalAngel** [comment]
Added now through https://github.com/divio/djangocms-googlemap/pull/46

**Pull request closed without merging**
